version: '3.9'

services:
  laravel:
    build: .
    container_name: laravel_app
    ports:
      - '8000:9000'
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  vite:
    image: node:22
    container_name: vite_dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - '5173:5173'
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
